#%Module1.0
set compiler "nocompiler"
set mpi ""
if {[module-info mode switch1] || [module-info mode switch3]} {
  set commandWords [split [exec /bin/ps -p [pid] -o args=] " "]
  set switchFrom [lindex [split [module-info name] "/"] 0]
  set switchTo [lindex [split [lindex $commandWords end] "/"] 0]
  set loadApps [expr  [string equal $switchTo $switchFrom]]
} elseif {[module-info mode remove]} {
  set loadApps 0
} else {
   set loadApps 1
}
if { $loadApps  }  {
 if {[info exists env(LOADEDMODULES)]} {
  foreach app [split $env(LOADEDMODULES) ":"] {
     if { [ string match "*intel*" $app ] == 1 } {
          set compiler "intel"
     } elseif { [ string match "*pgi*" $app ] == 1 } {
          set compiler "pgi"
     } elseif { [ string match "*gnu*" $app ] == 1 && [ string match *gnutools* $app ] == 0 } {
          set compiler "gnu"
     }
     if { [ string match "*mvapich2_ib*" $app ] == 1 } {
          set mpi "mvapich2_ib"
     } elseif { [ string match "*openmpi_ib*" $app ] == 1 } {
          set mpi "openmpi_ib"
     } elseif { [ string match "*mpich2_ib*" $app ] == 1 } {
          set mpi "mpich2_ib"
     }
  }
 }

 if { [ string equal "nocompiler" $compiler ] ==  1 } {
      module load COMPILERNAME
      module load MPINAME
  } elseif { [ string equal "COMPILERNAME" $compiler ] ==  1 } {
      module unload ${mpi}
      module load MPINAME
  } else {
      module unload $compiler
      module load COMPILERNAME
      module load MPINAME
  }
}
prepend-path PATH /opt/raxml/bin
